#WeatherNews Configuration
#Variables can be written in text
#In-Text Variables are written in form of ${Variablename}
#Variables are case sensitive
#Predefined Variables are
#Color:
#Black
#DarkBlue
#DarkGreen
#Teal
#DarkRed
#Purple
#Gold
#Gray
#DarkGray
#Blue
#BrightGreen
#Aqua
#Red
#Pink
#Yellow
#White
#Time:
#day
#hour
#minute
#currenthold
#change
#Format:
#newline
#Statesaver
#current
#next
#Special variables
#rain
#thunderstorm
#sun
#nextclear
#nextunclear

variables:
  - header:
      "${Gold}[WeatherNews] Today the day: ${day}${newline}
      We have ${current} for the next ${currenthold}"
  - clear:
      "and then we get ${next}"
  - unclear:
      "and something different after that.${newline}
      I will notice you in ${change}"
nextclear: "${header}${newline}${clear}"
nextunclear: "${header}${newline}${unclear}"