worldwhitelist: false
worlds:
- world_sample
- world_other
showonlogin: true
stepping:
- 1:
    minute: 1
- 60:
    minute: 10
- 240:
    minute: 30
- 360:
    minute: 0
    hour: 1
- 11520:
    minute: 0
    hour: 0
    day: 2
unprecise: true
minimumpercentage: 0.0
maximumpercentage: 1.0
exponentialmod: 2.0
modulator: 31
maximumtime: 36000
variables:
  DAY: "day"
  DAY_PLURAL: "days"
  HOUR: "hour"
  HOUR_PLURAL: "hours"
  MINUTE: "minute"
  MINUTE_PLURAL: "minutes"
  AND: "and"
  SUN: "sun"
  RAIN: "rain"
  THUNDERSTORM: "thunderstorm"
  CLEAR: "${header}${today}${mainclear}${nextclear}"
  UNCLEAR: "${header}${today}${mainunclear}${nextunclear}"
  UNAVAILABLE: "${header}${RED}Weather unavailable."
  BLACKLISTED: "${header}${RED}Sorry I can't do this."
  header: "${GOLD}[WeatherNews] "
  today: "Today the day ${TIMEDAY}. "
  nextunclear: |
    After that we have something different.
    I will notice you in ${NEXTNICE}.
  nextclear: "After that we have ${NEXT}."
  mainclear: |
    We have ${NOW} for the next ${NEXTNICE}.
  mainunclear: |
    We have at least ${NOW} for the next ${NEXTNICE}.
